In [ ]:
import numpy as np
import pandas as pd
import torch

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder

In [ ]:
data = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
data.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [ ]:
data.dtypes

id                           int64
diagnosis                   object
radius_mean                float64
texture_mean               float64
perimeter_mean             float64
area_mean                  float64
smoothness_mean            float64
compactness_mean           float64
concavity_mean             float64
concave points_mean        float64
symmetry_mean              float64
fractal_dimension_mean     float64
radius_se                  float64
texture_se                 float64
perimeter_se               float64
area_se                    float64
smoothness_se              float64
compactness_se             float64
concavity_se               float64
concave points_se          float64
symmetry_se                float64
fractal_dimension_se       float64
radius_worst               float64
texture_worst              float64
perimeter_worst            float64
area_worst                 float64
smoothness_worst           float64
compactness_worst          float64
concavity_worst            float64
concave points_worst       float64
symmetry_worst             float64
fractal_dimension_worst    float64
Unnamed: 32                float64
dtype: object

In [ ]:
data.drop(columns=['id', 'Unnamed: 32'], inplace= True)

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(data.iloc[:, 1:], data.iloc[:, 0], test_size=0.2)

In [ ]:
X_train.head()

radius_mean  texture_mean  perimeter_mean  area_mean  smoothness_mean  \
213        17.42         25.56          114.50      948.0          0.10060   
220        13.65         13.16           87.88      568.9          0.09646   
300        19.53         18.90          129.50     1217.0          0.11500   
549        10.82         24.21           68.89      361.6          0.08192   
42         19.07         24.81          128.30     1104.0          0.09081   

     compactness_mean  concavity_mean  concave points_mean  symmetry_mean  \
213           0.11460         0.16820              0.06597         0.1308   
220           0.08711         0.03888              0.02563         0.1360   
300           0.16420         0.21970              0.10620         0.1792   
549           0.06602         0.01548              0.00816         0.1976   
42            0.21900         0.21070              0.09961         0.2310   

     fractal_dimension_mean  ...  radius_worst  texture_worst  \
213                 0.05866  ...         18.07          28.07   
220                 0.06344  ...         15.34          16.35   
300                 0.06552  ...         25.93          26.24   
549                 0.06328  ...         13.03          31.45   
42                  0.06343  ...         24.09          33.17   

     perimeter_worst  area_worst  smoothness_worst  compactness_worst  \
213           120.40      1021.0            0.1243             0.1793   
220            99.71       706.2            0.1311             0.2474   
300           171.10      2053.0            0.1495             0.4116   
549            83.90       505.6            0.1204             0.1633   
42            177.40      1651.0            0.1247             0.7444   

     concavity_worst  concave points_worst  symmetry_worst  \
213          0.28030               0.10990          0.1603   
220          0.17590               0.08056          0.2380   
300          0.61210               0.19800          0.2968   
549          0.06194               0.03264          0.3059   
42           0.72420               0.24930          0.4670   

     fractal_dimension_worst  
213                  0.06818  
220                  0.08718  
300                  0.09929  
549                  0.07626  
42                   0.10380  

[5 rows x 30 columns]

In [ ]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [ ]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [ ]:
X_train_tensor = torch.from_numpy(X_train)
X_test_tensor = torch.from_numpy(X_test)
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)

# **Define Neural Network**

In [ ]:
class MySimpleNN():

  def __init__(self, X):

    self.weights = torch.rand(X.shape[1], 1, dtype=torch.float64, requires_grad=True)
    self.bias = torch.zeros(1, dtype=torch.float64, requires_grad=True)

  def forward(self, X):
    z = torch.matmul(X, self.weights) + self.bias
    y_pred = torch.sigmoid(z)
    return y_pred

  def loss_function(self, y_pred, y):
    # Clamp predictions to avoid log(0)
    epsilon = 1e-7
    y_pred = torch.clamp(y_pred, epsilon, 1 - epsilon)
    # Calculate loss
    loss = -(y_train_tensor * torch.log(y_pred) + (1 - y_train_tensor) * torch.log(1 - y_pred)).mean()
    return loss



In [ ]:
learning_rate = 0.1
epochs = 25

# **Training Pipeline**

In [ ]:
model = MySimpleNN(X_train_tensor)
# model.weights

In [ ]:
model.bias

tensor([0.], dtype=torch.float64, requires_grad=True)

In [ ]:
# define loop

for epoch in range(epochs):

  # forward_pass
  y_pred = model.forward(X_train_tensor)
  # print(y_pred)

  # loss_cal
  loss = model.loss_function(y_pred, y_train_tensor)

  # backward_pass
  loss.backward()

  # parameter update
  with torch.no_grad():
    model.weights -= learning_rate * model.weights.grad
    model.bias -= learning_rate * model.bias.grad

  # zero gradients
  model.weights.grad.zero_()
  model.bias.grad.zero_()

  # print loss in each epoch
  print(f'Epoch: {epoch + 1}, Loss: {loss.item()}')

Epoch: 1, Loss: 3.7196548801304345
Epoch: 2, Loss: 3.6058899093950783
Epoch: 3, Loss: 3.486672303760283
Epoch: 4, Loss: 3.363345629533002
Epoch: 5, Loss: 3.2362729581680205
Epoch: 6, Loss: 3.106318945353889
Epoch: 7, Loss: 2.9760845845584636
Epoch: 8, Loss: 2.841133878511128
Epoch: 9, Loss: 2.7035260825432803
Epoch: 10, Loss: 2.5594225745689667
Epoch: 11, Loss: 2.418804045180422
Epoch: 12, Loss: 2.280070160761088
Epoch: 13, Loss: 2.143943304648524
Epoch: 14, Loss: 2.004328421718273
Epoch: 15, Loss: 1.8675539603931903
Epoch: 16, Loss: 1.7333418886466878
Epoch: 17, Loss: 1.6083101788064986
Epoch: 18, Loss: 1.4933949078029374
Epoch: 19, Loss: 1.388893793250111
Epoch: 20, Loss: 1.2896997622451971
Epoch: 21, Loss: 1.2035856982861908
Epoch: 22, Loss: 1.130459801489533
Epoch: 23, Loss: 1.069556557938064
Epoch: 24, Loss: 1.019576750586516
Epoch: 25, Loss: 0.9789017233427433


In [ ]:
model.bias

tensor([-0.1376], dtype=torch.float64, requires_grad=True)

In [ ]:
model.weights

tensor([[ 0.1532],
        [ 0.0409],
        [-0.1802],
        [-0.2730],
        [ 0.3726],
        [ 0.2105],
        [-0.0218],
        [ 0.1428],
        [ 0.1315],
        [-0.1593],
        [ 0.2292],
        [ 0.2980],
        [ 0.3010],
        [-0.2331],
        [ 0.6293],
        [ 0.3310],
        [-0.1084],
        [-0.1098],
        [ 0.5129],
        [-0.2691],
        [-0.0029],
        [ 0.5470],
        [ 0.0277],
        [-0.2291],
        [-0.0272],
        [-0.1247],
        [ 0.2011],
        [-0.1675],
        [ 0.3561],
        [-0.2406]], dtype=torch.float64, requires_grad=True)

In [ ]:
# model evaluation
with torch.no_grad():
  y_pred = model.forward(X_test_tensor)
  y_pred = (y_pred > 0.5).float()
  accuracy = (y_pred == y_test_tensor).float().mean()
  print(f'Accuracy: {accuracy.item()}')

Accuracy: 0.5069252252578735
