In [1]:
import torch
print(torch.__version__)

2.5.1+cu124


In [3]:
if torch.cuda.is_available():
  print(f'GPU is available')
  print(f'Using GPU: {torch.cuda.get_device_name(0)}')
else:
  print(f'running on CPU')

GPU is available
Using GPU: Tesla T4


# **Creating a Tensor**




In [6]:
a = torch.empty(2,3)
type(a)

torch.Tensor

In [7]:
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [9]:
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [10]:
torch.rand(2,3)

tensor([[0.1628, 0.8229, 0.6604],
        [0.3758, 0.7868, 0.7735]])

# **Tensor Shapes**

In [12]:
x = torch.tensor([[1,2,3],[4,5,6]])

In [13]:
x.shape

torch.Size([2, 3])

# **Data Types**

In [15]:
torch.tensor([1.0,2.0,3.0], dtype=torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [19]:
x = torch.tensor(3.0, requires_grad=True)

In [20]:
y = x ** 2

In [21]:
x

tensor(3., requires_grad=True)

In [22]:
y

tensor(9., grad_fn=<PowBackward0>)

In [23]:
y.backward()

In [24]:
x.grad

tensor(6.)